# to program to arduino, type make flash
CC=avr-g++
CFLAGS = -Wno-write-strings
BINARY_NAME = cpp-binary

# required
SOURCES = $(wildcard *.cpp)
INCLUDES = ./

# specify your preferred .mk file
include ../../common/without-os.mk
