# to program to arduino, type make flash
CPP_PROJECT = yes
PROJECT_NAME = cpp-sample

# required
SOURCES = $(wildcard *.cpp)
INCLUDES = ./

# always include skeleton.mk
include ../../common/skeleton.mk
