# to program to arduino, type make flash
IDE_SUPPORT = yes
PROJECT_NAME = ide-sample
CFLAGS = -fdata-sections -ffunction-sections -Wl,--gc-sections

# always include skeleton.mk
include ../../../common/skeleton.mk
