# to program to arduino, type make flash
CC=avr-gcc
CFLAGS = 
BINARY_NAME = c-binary

# required
SOURCES = $(wildcard *.c)
INCLUDES = ./

# specify your preferred .mk file
include ../../common/without-os.mk
