# to program to arduino, type make flash
IDE_SUPPORT = yes
PROJECT_NAME = ide-sample

# required
SOURCES = $(wildcard *.cpp)
INCLUDES = ./

# always include skeleton.mk
include ../../common/skeleton.mk
