# to program to arduino, type make flash
CC=avr-gcc
CFLAGS =
DEBUG = yes
UTILS_SUPPORT = yes

# required
TOP = ../../
SOURCES = $(wildcard *.c)
INCLUDES = ./

# specify your preferred .mk file
include ../../common/without-os.mk
