# This only support unit test, no actual project is here

# required
TOP = ../../
INCLUDES = ./

# unit test files
# remember to put cxx test headers in test/*Test.h
TEST_SOURCES = AVRString.c
TEST_DEBUG = no
TEST_CFLAGS = -std=gnu++0x

# specify your preferred .mk file
include $(TOP)/common/unittest.mk

