# This only support unit test, no actual project is here

# required
TOP = ../../
INCLUDES = ./

# unit test files
# remember to put cxx test headers in test/*Test.h
UNITTEST_SUPPORT = yes
TEST_SOURCES = AVRString.c
TEST_DEBUG = no
TEST_CFLAGS = -std=gnu++0x

# always include skeleton.mk
include $(TOP)/common/skeleton.mk

